@startuml
!theme xuanye from ../
title 基于微服务的 webservice 平台负载均衡方案


actor client

agent "webservice gateway"

cloud nacos/otherRegisterService {
    component "注册中心"
    component "配置中心"
}


node "webservice A node1"
node "webservice A node2"

node "webservice B node1"
node "webservice B node2"

client --> "webservice gateway"
"webservice gateway" --> "webservice A node1" #line:green;text:green  : "webservice A负 载 均 衡 与 高 可 用"
"webservice gateway" -[#green]-> "webservice A node2"
"webservice gateway" --> "webservice B node1" #line:blue;text:blue :  "webservice B负 载 均 衡 与 高 可 用"
"webservice gateway" -[#blue]-> "webservice B node2"

nacos <--> "webservice gateway" #aqua;line.dashed;text:aqua  :  "注 册 gateway 服 务 与 拉 取 路 由 信 息"
nacos <--> "webservice A node1" #orange;line.dashed
nacos <--> "webservice A node2" #orange;line.dashed
nacos <--> "webservice B node1" #orange;line.dashed
nacos <--> "webservice B node2" #line:orange;line.dashed;text:orange  :  "注 册 服 务 与 拉 取 配 置 文 件"


@enduml
